# Config 参数
SIZES = {
    'basic': 224
}

NUM_CHANNELS = 3
NUM_CLASSES = 5
GENERATOR_BATCH_SIZE = 64
TOTAL_EPOCHS = 150
STEPS_PER_EPOCH = 500
VALIDATION_STEPS = 50
BASE_DIR = r'D:\T_Demo\(dai)model\nsfw_model-1.1.0\titi\d'
